/**
 * The cast files that sit in an archive folder (ADR-0029).
 *
 * Two files, one line format:
 *
 *   `_pulseboard_cast.txt` — generated by the app, refreshed by the scan agent
 *   `_cast.txt`            — hand-written, read-only to the app
 *
 * Plain text rather than JSON for a specific reason: PowerShell's `ConvertTo-Json`
 * collapses a one-element array into a scalar, and a participant list is exactly the
 * shape that breaks when an agent rewrites JSON. Text has no such failure mode, and
 * it greps, diffs and reads by eye — which is the whole point of a file whose job is
 * to answer a question when nothing else is running.
 *
 * Every line is self-contained: `Name (ICG-ID)`, never an internal id. Picasa's
 * `.picasa.ini` pointed into a central contacts file, and a folder copied elsewhere
 * lost its names.
 */
import { createHash } from 'node:crypto'
import { ICG_ID_RE } from '@/lib/icg-id'

export type FilePerson = { name: string; icgId: string }

/**
 * Which of the two statements a person is part of (ADR-0028).
 *
 * `credited` — the cast of the set this folder is linked to; who the publisher named.
 * `claimed`  — the folder's own attributions; what the archive's owner asserts.
 */
export type PeopleSection = 'credited' | 'claimed'

export type ParsedPeopleFile = {
  credited: FilePerson[]
  claimed: FilePerson[]
  /** The `# revision:` header, when the file carries one (generated files do). */
  revision: string | null
  /** Lines that looked like an entry but were not usable — reported, never dropped. */
  errors: string[]
}

/** The app knows nobody here. The agent deletes a file that has outlived its content. */
export const EMPTY_REVISION = 'EMPTY'

export const APP_CAST_FILE = '_pulseboard_cast.txt'
export const HAND_CAST_FILE = '_cast.txt'
/** Written before 2026-08-09. The agent removes one when it writes the new name. */
export const LEGACY_APP_CAST_FILE = '_pulseboard_people.txt'

const SECTION_RE = /^#\s*(credited|claimed)\s*$/i
const REVISION_RE = /^#\s*revision\s*:\s*(\S+)\s*$/i
// `Name (ICG-ID)` — the name may contain anything except the trailing bracket pair.
const ENTRY_RE = /^(.*?)\s*\(([^()]+)\)\s*$/

/**
 * The written form of a name, reduced to the one thing that varies harmlessly.
 *
 * The catalogue names its folders `Iveta_C_(IC-87VY)`, a person types
 * `Iveta C (IC-87VY)`, and either may be lower-cased in passing. All three mean the
 * same person — and they do so because of the **ICG-ID**, which is the identity here;
 * the name is provenance. Normalising the separators keeps one person from appearing
 * as three differently-spelled entries, without pretending a name could identify
 * anyone by itself.
 *
 * Letters are left exactly as written: this is a display name, and deciding that
 * `iveta c` should be `Iveta C` is a guess the file has no business making.
 */
export function normalisePersonName(raw: string): string {
  return raw.replace(/_/g, ' ').replace(/\s+/g, ' ').trim()
}

/**
 * Read one line of either file.
 *
 * A bare ICG-ID is accepted and becomes its own name: the catalogue holds people
 * whose only known name *is* their ID, and a hand-written file should not force the
 * operator to invent one.
 */
export function parsePersonLine(line: string): FilePerson | null {
  const trimmed = line.trim()
  if (!trimmed) return null

  const withBrackets = ENTRY_RE.exec(trimmed)
  if (withBrackets) {
    const name = normalisePersonName(withBrackets[1])
    const icgId = withBrackets[2].trim().toUpperCase()
    if (!ICG_ID_RE.test(icgId)) return null
    return { name: name || icgId, icgId }
  }

  const bare = trimmed.toUpperCase()
  if (ICG_ID_RE.test(bare)) return { name: bare, icgId: bare }
  return null
}

/**
 * Read a whole file.
 *
 * Entries before any section marker count as **claims** — that is what a
 * hand-written `_cast.txt` is, and it carries no markers.
 */
export function parsePeopleFile(text: string): ParsedPeopleFile {
  const credited: FilePerson[] = []
  const claimed: FilePerson[] = []
  const errors: string[] = []
  let revision: string | null = null
  let section: PeopleSection = 'claimed'

  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim()
    if (!line) continue

    if (line.startsWith('#')) {
      const sectionMatch = SECTION_RE.exec(line)
      if (sectionMatch) section = sectionMatch[1].toLowerCase() as PeopleSection
      const revisionMatch = REVISION_RE.exec(line)
      if (revisionMatch) revision = revisionMatch[1]
      continue
    }

    const person = parsePersonLine(line)
    if (!person) {
      errors.push(line)
      continue
    }
    const target = section === 'credited' ? credited : claimed
    if (!target.some((p) => p.icgId === person.icgId)) target.push(person)
  }

  return { credited, claimed, revision, errors }
}

/**
 * A stable fingerprint of what the app knows about this folder.
 *
 * Sorted, so reordering does not churn the file; names included, so a rename
 * refreshes it. First 16 hex of SHA-256 — the same convention `contentSignature`
 * already uses on `ArchiveFolder`.
 */
export function peopleRevision(credited: FilePerson[], claimed: FilePerson[]): string {
  if (credited.length === 0 && claimed.length === 0) return EMPTY_REVISION
  const canonical = [
    'credited',
    ...canonicalise(credited),
    'claimed',
    ...canonicalise(claimed),
  ].join('\n')
  return createHash('sha256').update(canonical, 'utf8').digest('hex').slice(0, 16)
}

function canonicalise(people: FilePerson[]): string[] {
  return people
    .map((p) => `${p.icgId}|${p.name}`)
    .sort((a, b) => a.localeCompare(b))
}

export type RenderInput = {
  archiveKey: string
  folderName: string
  /** One line describing the linked set, or null when the folder is not linked. */
  setLine: string | null
  credited: FilePerson[]
  claimed: FilePerson[]
  generatedAt: Date
}

/**
 * The generated file, or null when there is nobody to write about — in which case
 * the agent removes any file that is already there.
 */
export function renderPeopleFile(input: RenderInput): string | null {
  const revision = peopleRevision(input.credited, input.claimed)
  if (revision === EMPTY_REVISION) return null

  const lines = [
    `# pulseboard — generated, do not edit. Your own entries belong in ${HAND_CAST_FILE}`,
    `# archiveKey: ${input.archiveKey}`,
    `# folder:     ${input.folderName}`,
    ...(input.setLine ? [`# set:        ${input.setLine}`] : []),
    `# revision:   ${revision}`,
    `# generated:  ${input.generatedAt.toISOString()}`,
  ]

  if (input.credited.length > 0) {
    lines.push('# credited', ...input.credited.map(formatPerson))
  }
  if (input.claimed.length > 0) {
    lines.push('# claimed', ...input.claimed.map(formatPerson))
  }

  return `${lines.join('\n')}\n`
}

/** `Name (ICG-ID)`, or the bare ID when the name adds nothing. */
export function formatPerson(person: FilePerson): string {
  return person.name && person.name !== person.icgId
    ? `${person.name} (${person.icgId})`
    : person.icgId
}
